# Generated by Django 6.0.1 on 2026-02-04 09:28

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sports_type', models.CharField(choices=[('GOLF', 'GOLF'), ('TENNIS', 'TENNIS'), ('CRICKET', 'CRICKET'), ('FOOTBALL', 'FOOTBALL'), ('BADMINTON', 'BADMINTON'), ('VOLLEYBALL', 'VOLLEYBALL'), ('PICKLEBALL', 'PICKLEBALL')], default='CRICKET', max_length=20)),
                ('price', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'court',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('USER', 'USER'), ('OWNER', 'OWNER'), ('ADMIN', 'ADMIN')], default='USER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gstno', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.court')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(default='06:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.business')),
            ],
            options={
                'db_table': 'turf',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='app.turf'),
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_default', models.BooleanField(default=False)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.turf')),
            ],
            options={
                'db_table': 'turf_image',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_no'], name='phone_no_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['id'], name='business_id_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['user'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['id'], name='booking_id_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['court'], name='booking_court_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_user_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_date_idx'),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['id'], name='turf_id_idx'),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['business'], name='business_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['id'], name='court_id_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['turf'], name='turf_idx'),
        ),
        migrations.AddIndex(
            model_name='turfimage',
            index=models.Index(fields=['id'], name='turf_image_id_idx'),
        ),
        migrations.AddIndex(
            model_name='turfimage',
            index=models.Index(fields=['turf'], name='turf_image_turf_idx'),
        ),
        migrations.AddConstraint(
            model_name='turfimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('turf',), name='unique_default_image_per_turf'),
        ),
    ]
