# Generated by Django 6.0.1 on 2026-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='sports_type',
            field=models.CharField(choices=[('GOLF', 'GOLF'), ('TENNIS', 'TENNIS'), ('CRICKET', 'CRICKET'), ('FOOTBALL', 'FOOTBALL'), ('BADMINTON', 'BADMINTON'), ('VOLLEYBALL', 'VOLLEYBALL'), ('PICKLEBALL', 'PICKLEBALL')], default='CRICKET', max_length=20),
        ),
        migrations.AddIndex(
            model_name='turfimage',
            index=models.Index(fields=['id'], name='turf_image_id_idx'),
        ),
        migrations.AddIndex(
            model_name='turfimage',
            index=models.Index(fields=['turf'], name='turf_image_turf_idx'),
        ),
        migrations.AlterModelTable(
            name='turfimage',
            table='turf_image',
        ),
    ]
